version: '3.3'
services:
  server:
    build: server
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_HOSTNAME: host1
    depends_on:
      - host1
      - host2

  server2:
    build: server
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_HOSTNAME: host1
    depends_on:
      - host1
      - host2

  host1:
    build: db/master
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MARIADB_ROOT_PASSWORD: 'root' #needs root rights for master-slave connection
  
  host2:
    build: db/slave
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MARIADB_ROOT_PASSWORD: 'root' #needs root rights for master-slave connection
    depends_on:
      - host1


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      PMA_HOST: host1
  
  phpmyadmin2:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8086:80
    environment:
      PMA_HOST: host2

  loadbalancer:
    build: loadbalancer
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - server
      - server2